version: '3.8'

services:
  db-master:
    image: mariadb:latest
    container_name: db-master
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_master_data:/var/lib/mysql
      - ./first.cnf:/etc/mysql/conf.d/replica.cnf
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    #expose:
      #- 3306
      #- 33060
    ports:
      - 3306:3306
    networks:
      - cangrownet

  db-replica:
    image: mariadb:latest
    container_name: db-replica
    command: '--default-authentication-plugin=mysql_native_password'
    volumes:
      - db_replica_data:/var/lib/mysql
      - ./second.cnf:/etc/mysql/conf.d/replica.cnf
    restart: unless-stopped
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
      - MYSQL_USER=$MYSQL_USER
      - MYSQL_PASSWORD=$MYSQL_PASSWORD
    #expose:
      #- 3306
      #- 33060
    ports:
      - 3307:3306
    depends_on:
      - db-master  
    networks:
      - cangrownet


  wordpress-1:
    image: wordpress:latest  
    container_name: wordpress-1
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8001:80"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db-master
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db-master
    networks:
      - cangrownet

  wordpress-2:
    image: wordpress:latest
    container_name: wordpress-2
    volumes:
      - wp_data:/var/www/html
    ports:
      - "8002:80"
    restart: unless-stopped
    environment:
      - WORDPRESS_DB_HOST=db-master
      - WORDPRESS_DB_USER=wordpress
      - WORDPRESS_DB_PASSWORD=wordpress
      - WORDPRESS_DB_NAME=wordpress
    depends_on:
      - db-master
    networks:
      - cangrownet         

  nginx:
    image: nginx:latest
    container_name: nginx  
    ports:
      - "80:80"
    depends_on:
      - wordpress-1
      - wordpress-2 
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf  
    restart: unless-stopped
    networks:
      - cangrownet       
   
volumes:
  db_master_data:
  db_replica_data:
  wp_data:

networks:
  cangrownet:
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/28
